# Generated by Django 5.2 on 2026-04-01 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='CONFIRMED', max_length=20)),
                ('payment_method', models.CharField(choices=[('ONLINE', 'Pay Online'), ('AT_SHOP', 'Pay at Shop')], max_length=20)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('total_price', models.PositiveIntegerField(help_text='Total in UZS, snapshotted at booking time')),
                ('total_duration', models.PositiveSmallIntegerField(help_text='Total minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(limit_choices_to={'role': 'BARBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='barber_appointments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_price', models.PositiveIntegerField()),
                ('service_duration', models.PositiveSmallIntegerField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_services', to='bookings.appointment')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='appointments', through='bookings.AppointmentService', to='services.service'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['barber', 'date', 'status'], name='bookings_ap_barber__7ffd16_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer', 'status'], name='bookings_ap_custome_7316db_idx'),
        ),
    ]
