# Generated by Django 5.2 on 2026-04-22 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('barber', 'date', 'start_time'), name='unique_confirmed_slot_per_barber'),
        ),
    ]
